version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - exhaustive
    - gocyclo
    - nlreturn
    - predeclared
    - revive
    - wrapcheck
  settings:
    revive:
      confidence: 0.8
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
