// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {split} from '../models';
import {persist} from '../models';

export function CheckSuspendedRun():Promise<Record<string, any>>;

export function ConfirmDialog(arg1:string,arg2:string):Promise<boolean>;

export function CreateAttempts(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function CreateTemplate(arg1:string,arg2:Array<string>):Promise<Record<string, any>>;

export function DeleteAttempts(arg1:string):Promise<boolean>;

export function DeleteSingleAttempt(arg1:string,arg2:number):Promise<Record<string, any>>;

export function DeleteTemplate(arg1:string):Promise<boolean>;

export function DiscardAttempt():Promise<void>;

export function DiscardSuspendedRun():Promise<void>;

export function EditAttemptSplits(arg1:string,arg2:number,arg3:Array<number>):Promise<Record<string, any>>;

export function GetAppInfo():Promise<Record<string, any>>;

export function GetAttemptHistory(arg1:string):Promise<Array<split.Attempt>>;

export function GetCurrentAttempts():Promise<Record<string, any>>;

export function GetCurrentTemplate():Promise<Record<string, any>>;

export function GetDeltas():Promise<Array<split.Delta>>;

export function GetSettings():Promise<persist.Settings>;

export function ListAttemptsForTemplate(arg1:string):Promise<Array<persist.AttemptsSummary>>;

export function ListTemplates():Promise<Array<persist.TemplateSummary>>;

export function LoadAttempts(arg1:string):Promise<Record<string, any>>;

export function LoadTemplate(arg1:string):Promise<Record<string, any>>;

export function Reset():Promise<void>;

export function ResumeSuspendedRun():Promise<Record<string, any>>;

export function SkipSplit():Promise<void>;

export function StartSplit():Promise<void>;

export function SuspendRun():Promise<void>;

export function TogglePause():Promise<void>;

export function UndoSplit():Promise<void>;

export function UpdateCategoryName(arg1:string,arg2:string):Promise<Record<string, any>>;

export function UpdateSettings(arg1:persist.Settings):Promise<boolean>;

export function UpdateTemplate(arg1:string,arg2:string,arg3:Array<string>):Promise<Record<string, any>>;
