// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAttempts(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateAttempts'](arg1, arg2, arg3);
}

export function CreateTemplate(arg1, arg2) {
  return window['go']['main']['App']['CreateTemplate'](arg1, arg2);
}

export function DeleteAttempts(arg1) {
  return window['go']['main']['App']['DeleteAttempts'](arg1);
}

export function DeleteSingleAttempt(arg1, arg2) {
  return window['go']['main']['App']['DeleteSingleAttempt'](arg1, arg2);
}

export function DeleteTemplate(arg1) {
  return window['go']['main']['App']['DeleteTemplate'](arg1);
}

export function DiscardAttempt() {
  return window['go']['main']['App']['DiscardAttempt']();
}

export function EditAttemptSplits(arg1, arg2, arg3) {
  return window['go']['main']['App']['EditAttemptSplits'](arg1, arg2, arg3);
}

export function GetAttemptHistory(arg1) {
  return window['go']['main']['App']['GetAttemptHistory'](arg1);
}

export function GetCurrentAttempts() {
  return window['go']['main']['App']['GetCurrentAttempts']();
}

export function GetCurrentTemplate() {
  return window['go']['main']['App']['GetCurrentTemplate']();
}

export function GetDeltas() {
  return window['go']['main']['App']['GetDeltas']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListAttemptsForTemplate(arg1) {
  return window['go']['main']['App']['ListAttemptsForTemplate'](arg1);
}

export function ListTemplates() {
  return window['go']['main']['App']['ListTemplates']();
}

export function LoadAttempts(arg1) {
  return window['go']['main']['App']['LoadAttempts'](arg1);
}

export function LoadTemplate(arg1) {
  return window['go']['main']['App']['LoadTemplate'](arg1);
}

export function Reset() {
  return window['go']['main']['App']['Reset']();
}

export function SkipSplit() {
  return window['go']['main']['App']['SkipSplit']();
}

export function StartSplit() {
  return window['go']['main']['App']['StartSplit']();
}

export function TogglePause() {
  return window['go']['main']['App']['TogglePause']();
}

export function UndoSplit() {
  return window['go']['main']['App']['UndoSplit']();
}

export function UpdateCategoryName(arg1, arg2) {
  return window['go']['main']['App']['UpdateCategoryName'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateTemplate(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTemplate'](arg1, arg2, arg3);
}
